name: playground
on:
  push:
    branches:
      - master
jobs:

  linux_job:
    name: Check xx platform
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1
        working-directory: build/hi
      - name: ls
        run: dir
      - name: Build something requiring CL.EXE
        run: lib /def:drilldotnet.def /out:libnative.lib


